# Generated by Django 5.2.10 on 2026-01-27 15:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DHIS2Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Server identifier name', max_length=100, unique=True)),
                ('url', models.URLField(help_text='DHIS2 instance base URL (e.g., https://dhis2.example.org)')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(help_text='Encrypted or plain password', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DHIS2 Server',
                'verbose_name_plural': 'DHIS2 Servers',
                'db_table': 'dhis2_servers',
            },
        ),
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('dhis2_dataset_uid', models.CharField(help_text='DHIS2 DataSet UID', max_length=11, unique=True)),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], default='MONTHLY', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='sync.dhis2server')),
            ],
            options={
                'verbose_name': 'DataSet',
                'verbose_name_plural': 'DataSets',
                'db_table': 'datasets',
            },
        ),
        migrations.CreateModel(
            name='FacilityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlmis_facility_code', models.CharField(db_index=True, help_text='OpenLMIS facility code (e.g., D001)', max_length=50, unique=True)),
                ('openlmis_facility_name', models.CharField(blank=True, help_text='OpenLMIS facility name for reference', max_length=255)),
                ('dhis2_org_unit_id', models.CharField(db_index=True, help_text='DHIS2 Organisation Unit UID (e.g., buhtSZIesYb)', max_length=11)),
                ('dhis2_org_unit_name', models.CharField(blank=True, help_text='DHIS2 org unit name for reference', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this facility should be synced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='sync.dhis2server')),
            ],
            options={
                'verbose_name': 'Facility Mapping',
                'verbose_name_plural': 'Facility Mappings',
                'db_table': 'facility_mappings',
            },
        ),
        migrations.CreateModel(
            name='AggregatedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, max_length=10)),
                ('openlmis_product_code', models.CharField(db_index=True, max_length=50)),
                ('indicator', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('RECEIVED', 'Received'), ('ISSUED', 'Issued'), ('ADJUSTMENT_POSITIVE', 'Positive Adjustment'), ('ADJUSTMENT_NEGATIVE', 'Negative Adjustment'), ('TOTAL_ADJUSTMENT', 'Total Adjustment (Net)'), ('CLOSING_BALANCE', 'Closing Balance'), ('STOCK_ON_HAND', 'Stock on Hand'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dhis2_data_element_uid', models.CharField(max_length=11)),
                ('dhis2_category_option_combo_uid', models.CharField(blank=True, max_length=11)),
                ('dhis2_org_unit_id', models.CharField(max_length=11)),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_data', to='sync.facilitymapping')),
            ],
            options={
                'verbose_name': 'Aggregated Data',
                'verbose_name_plural': 'Aggregated Data',
                'db_table': 'aggregated_data',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(db_index=True, help_text='DHIS2 period format (e.g., 202511 for Nov 2025)', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('records_extracted', models.IntegerField(default=0)),
                ('records_transformed', models.IntegerField(default=0)),
                ('records_loaded', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed sync results including errors and warnings')),
                ('error_message', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='sync.facilitymapping')),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'db_table': 'sync_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cron_expression', models.CharField(help_text="Cron expression (e.g., '0 2 5 * *' for 02:00 on 5th of each month)", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datasets', models.ManyToManyField(blank=True, help_text='Datasets to sync (empty = all active datasets)', related_name='schedules', to='sync.dataset')),
                ('facilities', models.ManyToManyField(blank=True, help_text='Facilities to sync (empty = all active facilities)', related_name='schedules', to='sync.facilitymapping')),
            ],
            options={
                'verbose_name': 'Sync Schedule',
                'verbose_name_plural': 'Sync Schedules',
                'db_table': 'sync_schedules',
            },
        ),
        migrations.CreateModel(
            name='DataElementMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openlmis_product_code', models.CharField(db_index=True, help_text='OpenLMIS orderable/product code (e.g., BCG)', max_length=50)),
                ('openlmis_product_name', models.CharField(blank=True, help_text='Product name for reference', max_length=255)),
                ('indicator', models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('RECEIVED', 'Received'), ('ISSUED', 'Issued'), ('ADJUSTMENT_POSITIVE', 'Positive Adjustment'), ('ADJUSTMENT_NEGATIVE', 'Negative Adjustment'), ('TOTAL_ADJUSTMENT', 'Total Adjustment (Net)'), ('CLOSING_BALANCE', 'Closing Balance'), ('STOCK_ON_HAND', 'Stock on Hand'), ('EXPIRED', 'Expired'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost')], db_index=True, help_text='Type of stock movement indicator', max_length=30)),
                ('dhis2_data_element_uid', models.CharField(help_text='DHIS2 Data Element UID', max_length=11)),
                ('dhis2_data_element_name', models.CharField(blank=True, help_text='Data element name for reference', max_length=255)),
                ('dhis2_category_option_combo_uid', models.CharField(blank=True, default='', help_text='DHIS2 Category Option Combo UID (optional)', max_length=11)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_elements', to='sync.dataset')),
            ],
            options={
                'verbose_name': 'Data Element Mapping',
                'verbose_name_plural': 'Data Element Mappings',
                'db_table': 'data_element_mappings',
                'indexes': [models.Index(fields=['openlmis_product_code', 'indicator', 'is_active'], name='data_elemen_openlmi_9dc549_idx')],
                'unique_together': {('openlmis_product_code', 'indicator')},
            },
        ),
        migrations.AddIndex(
            model_name='facilitymapping',
            index=models.Index(fields=['openlmis_facility_code', 'is_active'], name='facility_ma_openlmi_5c845c_idx'),
        ),
        migrations.AddIndex(
            model_name='aggregateddata',
            index=models.Index(fields=['period', 'is_synced'], name='aggregated__period_3845f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='aggregateddata',
            unique_together={('facility', 'period', 'openlmis_product_code', 'indicator')},
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['facility', 'period'], name='sync_logs_facilit_474581_idx'),
        ),
        migrations.AddIndex(
            model_name='synclog',
            index=models.Index(fields=['status', 'started_at'], name='sync_logs_status_39138b_idx'),
        ),
    ]
