# Generated by Django 5.2.10 on 2026-03-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dataelementmapping',
            name='data_elemen_openlmi_9dc549_idx',
        ),
        migrations.RemoveIndex(
            model_name='facilitymapping',
            name='facility_ma_openlmi_5c845c_idx',
        ),
        migrations.RemoveField(
            model_name='facilitymapping',
            name='dhis2_org_unit_name',
        ),
        migrations.RemoveField(
            model_name='facilitymapping',
            name='openlmis_facility_code',
        ),
        migrations.RemoveField(
            model_name='facilitymapping',
            name='openlmis_facility_name',
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='openlmis_product_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataelementmapping',
            name='openlmis_product_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', help_text='OpenLMIS product UUID (from kafka_orderables.id)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facilitymapping',
            name='openlmis_facility_id',
            field=models.UUIDField(db_index=True, default='00000000-0000-0000-0000-000000000000', help_text='OpenLMIS facility UUID (from kafka_facilities.id)', unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='aggregateddata',
            unique_together={('facility', 'period', 'openlmis_product_id', 'indicator')},
        ),
        migrations.AlterUniqueTogether(
            name='dataelementmapping',
            unique_together={('openlmis_product_id', 'indicator')},
        ),
        migrations.AlterField(
            model_name='aggregateddata',
            name='indicator',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('RECEIPTS', 'Receipts'), ('CONSUMPTIONS', 'Consumptions'), ('LOSSES', 'Losses'), ('ADJUSTMENTS', 'Adjustments'), ('CLOSING_BALANCE', 'Closing Balance'), ('STOCKOUT_DAYS', 'Stockout Days')], max_length=30),
        ),
        migrations.AlterField(
            model_name='dataelementmapping',
            name='indicator',
            field=models.CharField(choices=[('OPENING_BALANCE', 'Opening Balance'), ('RECEIPTS', 'Receipts'), ('CONSUMPTIONS', 'Consumptions'), ('LOSSES', 'Losses'), ('ADJUSTMENTS', 'Adjustments'), ('CLOSING_BALANCE', 'Closing Balance'), ('STOCKOUT_DAYS', 'Stockout Days')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dhis2_dataset_uid',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='dhis2server',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='dhis2server',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dhis2server',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='facilitymapping',
            name='dhis2_org_unit_id',
            field=models.CharField(db_index=True, help_text='DHIS2 Organisation Unit UID', max_length=11),
        ),
        migrations.AlterField(
            model_name='facilitymapping',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='period',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='cron_expression',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='datasets',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='sync.dataset'),
        ),
        migrations.AlterField(
            model_name='syncschedule',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='schedules', to='sync.facilitymapping'),
        ),
        migrations.AddIndex(
            model_name='dataelementmapping',
            index=models.Index(fields=['openlmis_product_id', 'indicator', 'is_active'], name='data_elemen_openlmi_6a9fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitymapping',
            index=models.Index(fields=['openlmis_facility_id', 'is_active'], name='facility_ma_openlmi_c36a7f_idx'),
        ),
        migrations.RemoveField(
            model_name='aggregateddata',
            name='openlmis_product_code',
        ),
        migrations.RemoveField(
            model_name='dataelementmapping',
            name='dhis2_data_element_name',
        ),
        migrations.RemoveField(
            model_name='dataelementmapping',
            name='openlmis_product_code',
        ),
        migrations.RemoveField(
            model_name='dataelementmapping',
            name='openlmis_product_name',
        ),
    ]
