# Generated by Django 5.2.12 on 2026-04-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0002_remove_dataelementmapping_data_elemen_openlmi_9dc549_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitymapping',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Nom lisible de la structure de santé', max_length=255),
        ),
    ]
